add_newline = false

format = """
$username\
@\
$hostname\
[\uE0B0](fg:blue inverted)\
$directory\
[\uE0B0](fg:blue)\
[\uE0B0](fg:purple inverted)\
$git_branch\
$git_status\
[\uE0B0](fg:purple)\
[\uE0B0](fg:red inverted)\
$memory_usage\
$cmd_duration\
[\uE0B0](fg:red)\
$line_break\
$character"""

[username]
format = '  $user'
show_always = true

[hostname]
ssh_only = false
format = '$hostname '

[directory]
format = "[ $path ]($style)"
style = "fg:bright-white bg:blue"
truncation_length = 3
truncation_symbol = "../"

[git_branch]
style = "fg:bright-white bg:purple"
symbol = "\uE0A0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:bright-white bg:purple"
format = '[$all_status$ahead_behind ]($style)'

[memory_usage]
disabled = false
format = "[ ${ram} ]($style)"
style = "fg:bright-white bg:red"
threshold = 50

[cmd_duration]
format = "[ $duration ]($style)"
min_time = 16
style = "fg:bright-white bg:red"

[line_break]
disabled = false

[character]
success_symbol = "[\u276F](fg:green)"
error_symbol = "[\u276F](fg:red)"
